### ISSUE TITLE
It doesn't open

### ISSUE THREAD

**Issue by yagizcamo93** [fr-Pursuit/GTAVModdingLauncher#12]
Please help. Everytime I run the GtaVModdingLauncher.exe this error shows up.

---- GTA V Modding Launcher 0.5.5 crash report ---- 
Generated on 25.08.2016 21:03:58

-- Thrown exception -- 
System.MissingMethodException: Yöntem bulunamadı: '!!0[] System.Array.Empty()'. 
konum: GTAVModdingLauncher.Launcher.InitLauncher() 
konum: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) 
konum: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) 
konum: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) 
konum: System.Threading.ThreadHelper.ThreadStart()

-- Launcher state -- 
Is initialized: True 
Is window initialized: True

-- UI state -- 
Selected profile index: 0 
Selected profile: ~Unexpected error~ 
Is working: False 
Are buttons enabled: False

[crash-25-08-2016-20.54.56.txt](https://github.com/fr-Pursuit/GTAVModdingLauncher/files/437768/crash-25-08-2016-20.54.56.txt)

[latest.txt](https://github.com/fr-Pursuit/GTAVModdingLauncher/files/437773/latest.txt)

**Comment by fr-Pursuit** [comment]
Please make sure you have .NET framework 4.6. If not, download and install it (the link is provided on the gta5-mods.com download page). If this fixed your problem, please close this issue. If not, comment back.

**Comment by yagizcamo93** [comment]
It solved the issue but now when I enter the game it stops working immediately.

**Comment by fr-Pursuit** [comment]
Maybe one of the mods you have isn't compatible with .NET 4.6. What mods do you have ?

**Comment by yagizcamo93** [comment]
I have native trainer: https://tr.gta5-mods.com/scripts/enhanced-native-trainer
           car mods: https://tr.gta5-mods.com/vehicles/nissan-skyline-gt-r-bnr34-yca-y97y
                            https://tr.gta5-mods.com/vehicles/1968-ford-mustang-fastback
                            https://tr.gta5-mods.com/vehicles/ford-mustang-gt-nfs-gt500-2013-add-on
                            https://tr.gta5-mods.com/vehicles/chevrolet-impala-67

**Comment by fr-Pursuit** [comment]
That's weird... None of this is related to .NET
So the problem isn't related to the .NET update, but to something else. Keep in mind that if you modified the root .rpf files (if you don't use a mods folder), the launcher will not work properly (it will not remove the rpf mods, but it will remove the thing that make the mods work without crashing, aka openiv.asi). So, I have a few questions to ask:

-Do you use the steam or the retail version
-Did you modified root rpf files or do you use a mods folder
-When you first launched the game, the selected profile was "modded" or "vanilla" ? If it is "modded", did you switch to "vanilla" ? If so, does switching back to "modded" makes the game work properly ? 

Thanks !

**Comment by yagizcamo93** [comment]
-I use steam version.
-I use OpenIV and mods folder for mods
-When I first launched it, there wasn't any mod so the selected profile was vanilla. I installed mods in mods folder but when I launched GTAVModdingLauncher, there was still no other profile except vanilla. Then I created a new profile and launched with the new profile.

**Comment by fr-Pursuit** [comment]
Does it still crash when you launch the vanilla profile ?

**Comment by yagizcamo93** [comment]
No it runs perfectly when I launch the vanilla profile. I played 1 hour and it didn't crash.

**Comment by fr-Pursuit** [comment]
In that case, the crash is probably due to an RPF mod that isn't installed correctly. To confirm this statement, please rename your "mods" folder to "mods_old" and launcher your modded profile.

PS: open the launcher, select the modded profile and click on the folder icon to open the directory where the "mods" folder is located.

**Comment by yagizcamo93** [comment]
After naming mods folder to mods_old it launched without problem but mods aren't working.

**Comment by fr-Pursuit** [comment]
That means you installed your car mods incorrectly, which is causing the crash. Please delete your mods folder and reinstall them.

**Comment by yagizcamo93** [comment]
I've reinstalled the mods and I'm sure that I installed them correctly. It still crashes.

**Comment by fr-Pursuit** [comment]
That means there's a problem with the mods.

**Comment by yagizcamo93** [comment]
I'll test mods separately and inform you.

**Comment by yagizcamo93** [comment]
Ok, "https://tr.gta5-mods.com/vehicles/ford-mustang-gt-nfs-gt500-2013-add-on" that's the mod causing crash. Thanks for everything. Your mod is awesome.

**Comment by fr-Pursuit** [comment]
Thanks :) I'm happy you solved your issue.
