### ISSUE TITLE
Activation required problem

### ISSUE THREAD

**Issue by yagizcamo93** [fr-Pursuit/GTAVModdingLauncher#29]
One week ago launcher was running properly without problems but when I updated the game it says activation required. I'm starting the game with vanilla profile and there is no problem but when I'm starting the modded profile, game gives me a warning says activation required.
![activation required](https://cloud.githubusercontent.com/assets/21247372/24330161/57b4571c-1221-11e7-82e3-69a69e502efa.png)

**Comment by fr-Pursuit** [comment]
In the settings, uncheck "Launch modded profiles in offline mode" and see if it fixes the issue.

**Comment by yagizcamo93** [comment]
Thanks for your immediate help, it fixed the issue. I assume as long as I enter the story mode I won't be banned.

**Comment by fr-Pursuit** [comment]
Indeed. The offline mode just makes sure you don't enter online, but isn't necessary.

I'm happy you fixed your issue !
