### ISSUE TITLE
GTA 5 Error/Crash

### ISSUE THREAD

**Issue by NSGamingLennard** [fr-Pursuit/GTAVModdingLauncher#33]
I use my own Folder !

---- GTA V Modding Launcher 0.5.6 crash report ----
Generated on 17.07.2018 11:29:03

-- Thrown exception --
System.MissingMethodException: Methode nicht gefunden: "!!0[] System.Array.Empty()".
   bei GTAVModdingLauncher.Launcher.InitLauncher()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

-- Launcher state --
Is initialized: True
Is window initialized: True

-- UI state --
Selected profile index: 0
Selected profile: ~Unexpected error~
Is working: False
Are buttons enabled: False

**Comment by fr-Pursuit** [comment]
It looks like you don't have .NET Framework 4.6 on your computer. Installing it should fix your issue. You can download it here: https://www.microsoft.com/en-us/download/details.aspx?id=48130&wa=wsignin1.0

**Comment by fr-Pursuit** [comment]
The error must've been fixed by updating .NET Framework
