### ISSUE TITLE
My x64.rpf files are not modded, but the launcher says they are

### ISSUE THREAD

**Issue by OfficialCRUGG** [fr-Pursuit/GTAVModdingLauncher#35]
Hey there! The launcher says, that my files are modded, even though I only modded the files in the "Grand Theft Auto V - Redux" Directory and not my "Grand Theft Auto V" Directory

**Comment by fr-Pursuit** [comment]
Hello. Does it specifically say that a rpf file is modded, or that the game is modded in general? I know the GTAVLanguageSelect.exe file has been added by Rockstar since the last release, which cause the launcher to detect new games as modded. If that's your issue, then you can safely move the file out.

If not, that means one rpf file does not

**Comment by OfficialCRUGG** [comment]
It says "Your game's integrity could not be verified. Please make sure your x64.rpf files are not modded and try again." Pressing OK trys again and pressing Cancel closed the program.

**Comment by fr-Pursuit** [comment]
Indeed, this message means one or more RPF files do not have the right hash. You can use Steam embedded integrity verification tool to verify if this warning is pertinent (cf https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335). If Steam does not detect anything to correct, you can safely ignore the initial integrity verification procedure (just click on "no" when the launcher asks you to verify the game's integrity).

**Comment by OfficialCRUGG** [comment]
Okay. I just did the check, and steam tells me "Checked all files". Does that mean all files are okay?
![image](https://user-images.githubusercontent.com/25248999/61208546-f0e23400-a6f7-11e9-9d4d-f947b275059b.png)

**Comment by fr-Pursuit** [comment]
Yes, it should have verified your game and corrected any error. You can safely ignore the launcher's integrity verification procedure now.

**Comment by OfficialCRUGG** [comment]
Like I already said in the edit of my message before, I get this error now.
![image](https://user-images.githubusercontent.com/25248999/61208774-70700300-a6f8-11e9-969a-38267c775daa.png)
Could this be, because I have my GTA V installed in a different directory? (A:\Steam\steamapps\common\Grand Theft Auto V)
But why didn't it happen before I did the check in Steam?

**Comment by fr-Pursuit** [comment]
Hmm this should not happen. I might've overestimated the launcher's ability to detect a Steam installation. I'll implement the ability to specify a custom GTA V path in the next update.

In the meantime, you will unfortunately not be able to use the launcher without adding a key in the windows registry. If you are not experienced with the windows registry, I'd advise you against doing so.

**Comment by fr-Pursuit** [comment]
Version 0.6.0 allows you to specify a custom installation.
Your problem should therefore be fixed.
