### ISSUE TITLE
Incorrect vanilla x64a.rpf hash

### ISSUE THREAD

**Issue by droobey** [fr-Pursuit/GTAVModdingLauncher#36]
After getting the error "Your game's integrity could not be verified. Please make sure your x64.rpf files are not modded and try again.", I validated the files using steam and all was OK.

Seems the hash for x64a.rpf is now incorrect.

The new MD5 hash is edfbe6855ec32a21a698abc27a899341

After changing the hash in the source code and running, files validate via the launcher successfully.

**Comment by fr-Pursuit** [comment]
Indeed, Rockstar must've changed the hash. Well, I'm planning on removing that feature anyway. There's not much use keeping it since the game's integrity can be verified through Steam or RGL.

In the meantime, thanks for the PR !

**Comment by fr-Pursuit** [comment]
The integrity check system has been removed in 0.6.1.
Either Steam's or the vanilla launcher's should be enough if necessary.
