### ISSUE TITLE
Files not being put back into profile folder.

### ISSUE THREAD

**Issue by Celeron64** [fr-Pursuit/GTAVModdingLauncher#38]
When creating a profile, adding mods to it, and then quitting the game and setting the Vanilla profile to the active one, the mods in the other profile will not be moved back.

Instead, this will happen: http://cdn.celeron.me/i/Y9Ov.png

**Comment by fr-Pursuit** [comment]
This issue should be fixed in 0.6.1
Sorry for the inconvenience !
