### ISSUE TITLE
Launching EGS version of GTA V possible solution

### ISSUE THREAD

**Issue by mips1** [fr-Pursuit/GTAVModdingLauncher#39]
The following two options will allow you to launch GTA V without manual intervention for the EGS version:

`%windir%\explorer.exe "com.epicgames.launcher://apps/9d2d0eb64d5c44529cece33fe2a46482?action=launch&silent=true"`

-or-

`start "" "com.epicgames.launcher://apps/9d2d0eb64d5c44529cece33fe2a46482?action=launch&silent=true"`

**Comment by fr-Pursuit** [comment]
Implemented if 0.6.5
Please reopen the issue if it doesn't work.
