### ISSUE TITLE
Application refuses to launch despite .NET 5 Runtime being installed

### ISSUE THREAD

**Issue by sadboiweedpound** [fr-Pursuit/GTAVModdingLauncher#42]
I downloaded and installed .NET 5 Runtime on my machine, but whenever I launch the GTA V Modding Launcher I get a message that says I need .NET 5 Runtime installed. I have the launcher installed in the root of the same drive GTA V is installed in (if that matters). I haven't reported too many issues on GitHub before, so if you need any more info from me to help pinpoint the issue, please let me know and I'll get back to you as soon as I can.

**Comment by fr-Pursuit** [comment]
Make sure to install the x86 (32 bit) version along with the x64 (64 bit) version. .NET 5 is a bit weird when choosing between the 32 bit and the 64 bit version, so it's always best to have both installed.

**Comment by fr-Pursuit** [comment]
You need .NET *Desktop* Runtime for the launcher to work.
To be sure, you can install both the x86 and x64 version.
