### ISSUE TITLE
[Question] specify gta V path

### ISSUE THREAD

**Issue by fluffy-git** [fr-Pursuit/GTAVModdingLauncher#43]
Where do i specify the gta V path?

**Comment by fr-Pursuit** [comment]
You can select the GTA V installation used by the launcher either on the first run if the launcher is unable to automatically detect a GTA V installation, or anytime in the launcher settings (simply click on the "Manage installs" button)

**Comment by fr-Pursuit** [comment]
The issue seems to have been resolved, so I'm closing it.
If you have any more questions, feel free to open another issue.
