### ISSUE TITLE
The tool prompts me to download .NET 5, when already installed

### ISSUE THREAD

**Issue by Valdorz** [fr-Pursuit/GTAVModdingLauncher#47]
After installing the .NET 5.0.13 Desktop Runtime, I started the tool and it prompted me to install .NET, sending me to the official Microsoft page and then again downloading the installer only to see the Uninstall and Repair buttons as I think it realised I already had it installed. So I tried to install the .NET Runtime for console apps, and I still got the same result. I've also tried restarting the computer after each installation, and running the program with privileges but neither worked.

**Comment by fr-Pursuit** [comment]
Hello,

You need to download both the x64 and the x86 versions of the .NET 5 Desktop Runtime.

**Comment by Valdorz** [comment]
Thanks, it worked.
