### ISSUE TITLE
the program has encountered an unexpected error and cannot continue

### ISSUE THREAD

**Issue by 3mo0or10** [fr-Pursuit/GTAVModdingLauncher#6]

**Comment by fr-Pursuit** [comment]
Looks like a low-level crash. Please provide your Documents\Pursuit\GTA V Modding Launcher\latest.log

**Comment by 3mo0or10** [comment]
i cant

**Comment by 3mo0or10** [comment]
[crash-28-07-2016-12.37.05.txt](https://github.com/fr-Pursuit/GTAVModdingLauncher/files/388713/crash-28-07-2016-12.37.05.txt)

**Comment by 3mo0or10** [comment]
[Uploading latest.log…]()

**Comment by 3mo0or10** [comment]
???

**Comment by fr-Pursuit** [comment]
Please make sure you have .NET Framework 4.6

**Comment by fr-Pursuit** [comment]
If you can't upload latest.log, please copy / paste its content here

**Comment by fr-Pursuit** [comment]
Do you have the Steam or the Retail version ?

**Comment by fr-Pursuit** [comment]
Well, you haven't responded for a while, so I suppose that your issue is fixed.
